#!/usr/bin/env swift
import Foundation

// Keep the installed CLI's dependency inventory tied to the actual resolved build inputs.
let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
struct Manifest: Decodable { let synapseVersion: String }
struct Resolved: Decodable {
    struct Pin: Decodable {
        struct State: Decodable { let version: String }
        let identity: String
        let state: State
    }
    let pins: [Pin]
}
let manifest = try JSONDecoder().decode(Manifest.self, from: Data(contentsOf: root.appendingPathComponent("Runtime/Synapse/runtime-manifest.json")))
let resolved = try JSONDecoder().decode(Resolved.self, from: Data(contentsOf: root.appendingPathComponent("Package.resolved")))
guard let sdk = resolved.pins.first(where: { $0.identity == "matrix-rust-components-swift" }) else {
    fatalError("Matrix SDK is missing from Package.resolved")
}
// Normalize the resolved semver spelling (26.8.11) to the upstream release spelling (26.08.11).
let parts = sdk.state.version.split(separator: ".")
guard parts.count == 3, let month = Int(parts[1]) else { fatalError("Unexpected Matrix SDK version") }
let sdkVersion = "\(parts[0]).\(String(format: "%02d", month)).\(parts[2])"
let output = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "Sources/InboxPlusBridgeService/InboxPlusBuildVersions.swift"
let source = """
// Generated by Scripts/make-build-versions.swift — do not edit by hand.
public enum InboxPlusBuildVersions {
    public static let synapse = \(String(reflecting: manifest.synapseVersion))
    public static let matrixSDK = \(String(reflecting: sdkVersion))
}

"""
try Data(source.utf8).write(to: URL(fileURLWithPath: output), options: .atomic)
print("wrote \(output)")
